const cardsConfig = [
  {
    id: 1,
    category: "encyclopedie",
    title: "Codex Culinaire Celeste",
    typeCode: "EN",
    rectoFile: "En_R_Codex-Culinaire-Celeste.svg",
    versoFile: "En_V_Codex-Culinaire-Celeste.svg",
  },
  {
    id: 2,
    category: "encyclopedie",
    title: "Constelation d orion",
    typeCode: "EN",
    rectoFile: "En_R_constelation-d-orion.svg",
    versoFile: "En_V_constelation-d-orion.svg",
  },
  {
    id: 3,
    category: "encyclopedie",
    title: "Constelation de cupidon",
    typeCode: "EN",
    rectoFile: "En_R_constelation-de-cupidon.svg",
    versoFile: "En_V_constelation-de-cupidon.svg",
  },
  {
    id: 4,
    category: "encyclopedie",
    title: "Constelation de la lyre",
    typeCode: "EN",
    rectoFile: "En_R_constelation-de-la-lyre.svg",
    versoFile: "En_V_constelation-de-la-lyre.svg",
  },
  {
    id: 5,
    category: "encyclopedie",
    title: "Constelation de sagittaire",
    typeCode: "EN",
    rectoFile: "En_R_constelation-de-sagittaire.svg",
    versoFile: "En_V_constelation-de-sagittaire.svg",
  },
  {
    id: 6,
    category: "encyclopedie",
    title: "Constelation du lapin",
    typeCode: "EN",
    rectoFile: "En_R_constelation-du-lapin.svg",
    versoFile: "En_V_constelation-du-lapin.svg",
  },
  {
    id: 7,
    category: "encyclopedie",
    title: "Constelation du scorpion",
    typeCode: "EN",
    rectoFile: "En_R_constelation-du-scorpion.svg",
    versoFile: "En_V_constelation-du-scorpion.svg",
  },
  {
    id: 8,
    category: "encyclopedie",
    title: "Flan de lumière acidulé",
    typeCode: "EN",
    rectoFile: "En_R_flan-de-lumière-acidulé.svg",
    versoFile: "En_V_flan-de-lumière-acidulé.svg",
  },
  {
    id: 9,
    category: "encyclopedie",
    title: "Le carre de retissage",
    typeCode: "EN",
    rectoFile: "En_R_Le-carre-de-retissage.svg",
    versoFile: "En_V_Le-carre-de-retissage.svg",
  },
  {
    id: 10,
    category: "encyclopedie",
    title: "Le choeur suspendu",
    typeCode: "EN",
    rectoFile: "En_R_Le-choeur-suspendu.svg",
    versoFile: "En_V_Le-choeur-suspendu.svg",
  },
  {
    id: 11,
    category: "encyclopedie",
    title: "Le sextant",
    typeCode: "EN",
    rectoFile: "En_R_Le-sextant.svg",
    versoFile: "En_V_Le-sextant.svg",
  },
  {
    id: 12,
    category: "encyclopedie",
    title: "Le treizieme lueur",
    typeCode: "EN",
    rectoFile: "En_R_Le-treizieme-lueur.svg",
    versoFile: "En_V_Le-treizieme-lueur.svg",
  },
  {
    id: 13,
    category: "encyclopedie",
    title: "Niveau de resonance",
    typeCode: "EN",
    rectoFile: "En_R_Niveau-de-resonance.svg",
    versoFile: "En_V_Niveau-de-resonance.svg",
  },
  {
    id: 14,
    category: "encyclopedie",
    title: "Nymirea",
    typeCode: "EN",
    rectoFile: "En_R_Nymirea.svg",
    versoFile: "En_V_Nymirea.svg",
  },
  {
    id: 15,
    category: "encyclopedie",
    title: "Pain doux de poussiere",
    typeCode: "EN",
    rectoFile: "En_R_Pain-doux-de-poussiere.svg",
    versoFile: "En_V_Pain-doux-de-poussiere.svg",
  },
  {
    id: 16,
    category: "encyclopedie",
    title: "Riz au citron brule",
    typeCode: "EN",
    rectoFile: "En_R_Riz-au-citron-brule.svg",
    versoFile: "En_V_Riz-au-citron-brule.svg",
  },
  {
    id: 17,
    category: "encyclopedie",
    title: "Unite de poids par fleche",
    typeCode: "EN",
    rectoFile: "En_R_Unite-de-poids-par-fleche.svg",
    versoFile: "En_V_Unite-de-poids-par-fleche.svg",
  },
  {
    id: 18,
    category: "encyclopedie",
    title: "Vaisseau dans le ciel",
    typeCode: "EN",
    rectoFile: "En_R_Vaisseau-dans-le-ciel.svg",
    versoFile: "En_V_Vaisseau-dans-le-ciel.svg",
  },
  {
    id: 19,
    category: "encyclopedie",
    title: "Zone Du Ciel",
    typeCode: "EN",
    rectoFile: "En_R_Zone-Du-Ciel.svg",
    versoFile: "En_V_Zone-Du-Ciel.svg",
  },
  {
    id: 20,
    category: "encyclopedie",
    title: "Zubenelgenubi",
    typeCode: "EN",
    rectoFile: "En_R_Zubenelgenubi.svg",
    versoFile: "En_V_Zubenelgenubi.svg",
  },
  {
    id: 21,
    category: "enigme",
    title: "Coeur Viseur Fleche 3",
    typeCode: "E",
    rectoFile: "E_R_Coeur-Viseur-Fleche_3.svg",
    versoFile: "E_V_Coeur-Viseur-Fleche_3.svg",
  },
  {
    id: 22,
    category: "enigme",
    title: "L Accord des Trois 6",
    typeCode: "E",
    rectoFile: "E_R_L-Accord-des-Trois_6.svg",
    versoFile: "E_V_L-Accord-des-Trois_6.svg",
  },
  {
    id: 23,
    category: "enigme",
    title: "L ami silencieux 10",
    typeCode: "E",
    rectoFile: "E_R_L-ami-silencieux_10.svg",
    versoFile: "E_V_L-ami-silencieux_10.svg",
  },
  {
    id: 24,
    category: "enigme",
    title: "L l alignement 12",
    typeCode: "E",
    rectoFile: "E_R_L-l-alignement_12.svg",
    versoFile: "E_V_L-l-alignement_12.svg",
  },
  {
    id: 25,
    category: "enigme",
    title: "L trajectoire perdu 11",
    typeCode: "E",
    rectoFile: "E_R_L-trajectoire-perdu_11.svg",
    versoFile: "E_V_L-trajectoire-perdu_11.svg",
  },
  {
    id: 26,
    category: "enigme",
    title: "La Couleurs des Cordes 8",
    typeCode: "E",
    rectoFile: "E_R_La-Couleurs-des-Cordes_8.svg",
    versoFile: "E_V_La-Couleurs-des-Cordes_8.svg",
  },
  {
    id: 27,
    category: "enigme",
    title: "La Lumiere Juste 9",
    typeCode: "E",
    rectoFile: "E_R_La-Lumiere-Juste_9.svg",
    versoFile: "E_V_La-Lumiere-Juste_9.svg",
  },
  {
    id: 28,
    category: "enigme",
    title: "La Mémoire Des Cordes 5",
    typeCode: "E",
    rectoFile: "E_R_La-Mémoire-Des-Cordes_5.svg",
    versoFile: "E_V_La-Mémoire-Des-Cordes_5.svg",
  },
  {
    id: 29,
    category: "enigme",
    title: "La Partition Oubliee 7",
    typeCode: "E",
    rectoFile: "E_R_La-Partition-Oubliee_7.svg",
    versoFile: "E_V_La-Partition-Oubliee_7.svg",
  },
  {
    id: 30,
    category: "enigme",
    title: "La Partition Suspendu 4",
    typeCode: "E",
    rectoFile: "E_R_La-Partition-Suspendu_4.svg",
    versoFile: "E_V_La-Partition-Suspendu_4.svg",
  },
  {
    id: 31,
    category: "enigme",
    title: "La Saveur Juste 13",
    typeCode: "E",
    rectoFile: "E_R_La-Saveur-Juste_13.svg",
    versoFile: "E_V_La-Saveur-Juste_13.svg",
  },
  {
    id: 32,
    category: "enigme",
    title: "La trame eperpillee 14",
    typeCode: "E",
    rectoFile: "E_R_La-trame-eperpillee_14.svg",
    versoFile: "E_V_La-trame-eperpillee_14.svg",
  },
  {
    id: 33,
    category: "enigme",
    title: "Le secret des astres 15",
    typeCode: "E",
    rectoFile: "E_R_Le-secret-des-astres_15.svg",
    versoFile: "E_V_Le-secret-des-astres_15.svg",
  },
  {
    id: 34,
    category: "enigme",
    title: "Ombre du Bond 1",
    typeCode: "E",
    rectoFile: "E_R_Ombre-du-Bond_1.svg",
    versoFile: "E_V_Ombre-du-Bond_1.svg",
  },
  {
    id: 35,
    category: "enigme",
    title: "S Oriente dans le ciel 0",
    typeCode: "E",
    rectoFile: "E_R_S-Oriente-dans-le-ciel_0.svg",
    versoFile: "E_V_S-Oriente-dans-le-ciel_0.svg",
  },
  {
    id: 36,
    category: "enigme",
    title: "Vestige en Courbe 2",
    typeCode: "E",
    rectoFile: "E_R_Vestige-en-Courbe_2.svg",
    versoFile: "E_V_Vestige-en-Courbe_2.svg",
  },
  {
    id: 37,
    category: "histoire",
    title: "Ancrage 155",
    typeCode: "H",
    rectoFile: "H_R_Ancrage_155.svg",
    versoFile: "H_V_Ancrage_155.svg",
  },
  {
    id: 38,
    category: "histoire",
    title: "Appel Orion 1",
    typeCode: "H",
    rectoFile: "H_R_Appel-Orion_1.svg",
    versoFile: "H_V_Appel-orion_1.svg",
  },
  {
    id: 39,
    category: "histoire",
    title: "Echo Retrouve 171",
    typeCode: "H",
    rectoFile: "H_R_Echo-Retrouve_171.svg",
    versoFile: "H_V_Echo-Retrouve_171.svg",
  },
  {
    id: 40,
    category: "histoire",
    title: "Eveil Des Cordes 103",
    typeCode: "H",
    rectoFile: "H_R_Eveil-Des-Cordes_103.svg",
    versoFile: "H_V_Eveil-Des-Cordes_103.svg",
  },
  {
    id: 41,
    category: "histoire",
    title: "Harmonie dispersee 198",
    typeCode: "H",
    rectoFile: "H_R_Harmonie-dispersee_198.svg",
    versoFile: "H_V_Harmonie-dispersee_198.svg",
  },
  {
    id: 42,
    category: "histoire",
    title: "La Chromharmonie 716",
    typeCode: "H",
    rectoFile: "H_R_La-Chromharmonie_716.svg",
    versoFile: "H_V_La-Chromharmonie_716.svg",
  },
  {
    id: 43,
    category: "histoire",
    title: "La Le Dernier Fragment 485",
    typeCode: "H",
    rectoFile: "H_R_La-Le-Dernier-Fragment_485.svg",
    versoFile: "H_V_La-Le-Dernier-Fragment_485.svg",
  },
  {
    id: 44,
    category: "histoire",
    title: "La Le Dessin Interieur 677",
    typeCode: "H",
    rectoFile: "H_R_La-Le-Dessin-Interieur_677.svg",
    versoFile: "H_V_La-Le-Dessin-Interieur_677.svg",
  },
  {
    id: 45,
    category: "histoire",
    title: "La Le Port de Zubenelgenubi 380",
    typeCode: "H",
    rectoFile: "H_R_La-Le-Port-de-Zubenelgenubi_380.svg",
    versoFile: "H_V_La-Le-Port-de-Zubenelgenubi_380.svg",
  },
  {
    id: 46,
    category: "histoire",
    title: "La Riviere qui Murmure 365",
    typeCode: "H",
    rectoFile: "H_R_La-Riviere-qui-Murmure_365.svg",
    versoFile: "H_V_La-Riviere-qui-Murmure_365.svg",
  },
  {
    id: 47,
    category: "histoire",
    title: "Le Chant Retrouver 273",
    typeCode: "H",
    rectoFile: "H_R_Le-Chant-Retrouver_273.svg",
    versoFile: "H_V_Le-Chant-Retrouver_273.svg",
  },
  {
    id: 48,
    category: "histoire",
    title: "Le Liberation 41",
    typeCode: "H",
    rectoFile: "H_R_Le-Liberation_41.svg",
    versoFile: "H_V_Le-Liberation_41.svg",
  },
  {
    id: 49,
    category: "histoire",
    title: "Le Silence Se Tends 253",
    typeCode: "H",
    rectoFile: "H_R_Le-Silence-Se-Tends_253.svg",
    versoFile: "H_V_Le-Silence-Se-Tends_253.svg",
  },
  {
    id: 50,
    category: "histoire",
    title: "Les Cordes Retrouvées 285",
    typeCode: "H",
    rectoFile: "H_R_Les-Cordes-Retrouvées_285.svg",
    versoFile: "H_V_Les-Cordes-Retrouvées_285.svg",
  },
  {
    id: 51,
    category: "histoire",
    title: "Oublie Du Sagittaire 518",
    typeCode: "H",
    rectoFile: "H_R_Oublie-Du-Sagittaire_518.svg",
    versoFile: "H_V_Oublie-Du-Sagittaire_518.svg",
  },
  {
    id: 52,
    category: "histoire",
    title: "Recontre avec le Lapin 258",
    typeCode: "H",
    rectoFile: "H_R_Recontre-avec-le-Lapin_258.svg",
    versoFile: "H_V_Recontre-avec-le-Lapin_258.svg",
  },
];

export const cardDisplaySettings = {
  cardHeight: null,
};

export default cardsConfig;
